name: Build Executables

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r client_requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name FutureClient_${{ matrix.os }} main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: FutureClient_${{ matrix.os }}
        path: dist/