name: Build Executables

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        cd apps/WindowsApp
        pip install -r requirements.txt

    - name: Build executable
      run: |
        cd apps/WindowsApp
        pyinstaller --onefile --windowed client.py --name FutureClient

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-executable
        path: dist/
